name: Publish new release to Docker hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14.16.*
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.*

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        id: build_result
        run: npm run build -- --prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/aci-frontend:latest